name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Auto closed successfully!"
